services:
  web:
    image: nginx:latest
    ports:
      - ${APP_PORT}:80
    volumes:
      - .:/app
      - ./docker/nginx/app.conf:/etc/nginx/conf.d/default.conf
      - ./logs:/var/log/nginx
    links:
      - app

  app:
    build:
      dockerfile: docker/php/Dockerfile
      target: dev
    expose:
      - 9000
    volumes:
      - .:/app
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    depends_on:
      - db

  db:
    image: mysql:8
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./logs:/var/log/mysql
      - ./docker/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
    ports:
      - ${DATABASE_PORT}:3306
    environment:
      - MYSQL_DATABASE=${DATABASE_NAME}
      - MYSQL_USER=${DATABASE_USER}
      - MYSQL_PASSWORD=${DATABASE_PASSWORD}
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
